export const EventsController = {
  Events: `events`,
  Create: `events`,
  EventsDrp: `events/dropdown`,
  ExportToExcel: `events/export`,
  ExportAssignedEventsToExcel: (memberUserId: string) =>
    `events/members/${memberUserId}/export-assigned-events`,
  Delete: (id: string) => `events/${id}`,
  Publish: (id: string) => `events/${id}/publish`,
  Cancel: (id: string) => `events/${id}/cancel`,
  Postpone: (id: string) => `events/${id}/postpone`,
  GetBasicInfo: (id: string) => `events/${id}/basic-info`,
  GetOverview: (id: string) => `events/${id}/overview`,
  GetEventStatistics: (id: string) => `events/${id}/overview/statistics`,
  GetTermsAndConditions: (id: string) => `events/${id}/terms-and-conditions`,
  GetEventActivities: (id: string) => `events/${id}/activities`,
  GetEventAttachments: (id: string) => `events/${id}/attachments`,
  GetAssignedEventsForMember: (userId: string) => `events/members/${userId}/assigned-events`,
  UpdateBasicInfo: (id: string) => `events/${id}/basic-info`,
  UpdateDescription: (id: string) => `events/${id}/description`,
  UpdateLocation: (id: string) => `events/${id}/location`,
  UpdateTermsAndConditions: (id: string) => `events/${id}/terms-and-conditions`,
  UploadAttachments: (id: string) => `events/${id}/attachments`,
  UpdatePerformances: (id: string) => `events/${id}/performances`,
  DeleteAttachment: (eventId: string, id: string) =>
    `events/${eventId}/attachments/${id}`,
  UpdateEventMaxCapacity: (id: string) => `events/${id}/update-max-capacity`,
  // IncreaseEventMaxCapacity: (id: string) => `events/${id}/increase-max-capacity`,
  // EventsBeVendorId: (vendorId: string) => `events/by-vendor-id/${vendorId}`,
  // ExportVendorEvents: (vendorId: string) => `events/vendors/${vendorId}/export`,
  IncreaseEventMaxCapacity: (id: string) => `events/${id}/increase-max-capacity`,
  EventsBeVendorId: (vendorId: string) => `events/by-vendor-id/${vendorId}`,
  ExportVendorEvents: (vendorId: string) => `events/vendors/${vendorId}/export`,
};
